# NumPy

*NumPy stands for Numerical Python and it's a fundamental package for scientific computing in Python. NumPy provides Python with an extensive math library capable of performing numerical computations effectively and efficiently.*

## Download

NumPy (v 1.13.0) is included with Anaconda.

Install specific version:

```sh
# Use either one command
conda install numpy=X.XX
pip install --upgrade numpy==X.XX
```

## Docs

*NumPy is a remarkable math library and it has many functions and features. In these introductory lessons, we will only scratch the surface of what NumPy can do. If you want to learn more about NumPy, make sure you check out the NumPy Documentation:*

 - [NumPy Manual](https://docs.scipy.org/doc/numpy-1.13.0/contents.html)
 - [NumPy User Guide](https://numpy.org/devdocs/user/index.html)
 - [NumPy Reference](https://numpy.org/devdocs/reference/index.html)
 - [Scipy Lectures](http://www.scipy-lectures.org/intro/numpy/index.html)



In [1]:
# Why use NumPy?
import time
import numpy as np
x = np.random.random(10000000)

# Case 1
start = time.time()
sum(x) / len(x)
print("sum(x) / len(x): %.5fs" % (time.time() - start))

# Case 2
start = time.time()
np.mean(x)
print("numpy.mean(x): %.5fs" % (time.time() - start))

sum(x) / len(x): 1.61402s
numpy.mean(x): 0.01000s


## Features

*Even though Python lists are great on their own, NumPy has a number of key features that give it great advantages over Python lists. Below are a few convincingly strong features:*

- One such feature is **speed**. When performing operations on large arrays NumPy can often perform several orders of magnitude faster than Python lists. This speed comes from the nature of NumPy arrays being memory-efficient and from optimized algorithms used by NumPy for doing arithmetic, statistical, and linear algebra operations.

- Another great feature of NumPy is that it has **multidimensional array data structures** that can represent vectors and matrices. You will learn all about vectors and matrices in the Linear Algebra section of this course later on, and as you will soon see, a lot of machine learning algorithms rely on matrix operations. For example, when training a Neural Network, you often have to carry out many matrix multiplications. NumPy is optimized for matrix operations and it allows us to do Linear Algebra operations effectively and efficiently, making it very suitable for solving machine learning problems.

- Another great advantage of NumPy over Python lists is that NumPy has a large number of **optimized built-in mathematical functions**. These functions allow you to do a variety of complex mathematical computations very fast and with very little code (avoiding the use of complicated loops) making your programs more readable and easier to understand.

 - [The NumPy array: a structure for efficient numerical computation](https://hal.inria.fr/inria-00564007/document)
 
 
### 1-Dimensional array:

In [2]:
d1 = np.array([1,2,3,4,5])

print(d1)
print(type(d1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


### 2-Dimensional array:

In [3]:
d2 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
], dtype =np.int64)

print(d2)
print(type(d2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


### String array:

In [4]:
strings = np.array(['Hello', 'World'])

print(strings)
print(type(strings))

['Hello' 'World']
<class 'numpy.ndarray'>


### Shape

NumPy arrays have a [shape](https://numpy.org/devdocs/reference/generated/numpy.shape.html) to represent the array dimensions. The shape of an array is the size along each of its dimensions. For example, the shape of a rank 2 array will correspond to the number of rows and columns of the array.

In [5]:
# print shapes
print(d1.shape)
print(d2.shape)
print(strings.shape)

(5,)
(3, 3)
(2,)


### Data Type

The [type](https://numpy.org/doc/stable/reference/arrays.dtypes.html) tells us the data-type of the elements. Remember, a NumPy array is homogeneous, meaning all elements will have the same data-type.

- [List of NumPy data types](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.types.html)

In [6]:
print(d1.dtype)
print(d2.dtype)
print(strings.dtype)

int32
int64
<U5


### Size

The size attribute returns the number of elements in the array, eg. columns x rows for a 2d array.


In [7]:
print(d1.size)
print(d2.size)

5
9


### Convert Array to File

Once you create an ndarray, you may want to save it to a file to be read later or to be used by another program.


In [8]:
# Save array to file

# We create a rank 1 ndarray
x = np.array([1, 2, 3, 4, 5])

# We save x into the current directory as 
np.save('my_array.npy', x)

print('Saved array to file')

Saved array to file


In [9]:
# Load array from file
y = np.load('my_array.npy')

print(y, y.dtype)

[1 2 3 4 5] int32


### Create Arrays



In [10]:
# Create array of zeros from shape
print( np.zeros((3,4), dtype=np.int8))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [11]:
# Create array filled with ones
print( np.ones((2, 8), dtype=np.int16) )

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [12]:
# Create array filled with any constant
print( np.full((4,4), '/') )

[['/' '/' '/' '/']
 ['/' '/' '/' '/']
 ['/' '/' '/' '/']
 ['/' '/' '/' '/']]


In [13]:
# Create array filled with 5
print( np.eye(4, dtype=np.int8) )

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [24]:
# Tile array
print( np.tile([[1,2,3],[4,5,6],[7,8,9]], (3, 3)) )

[[1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6]
 [7 8 9 7 8 9 7 8 9]
 [1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6]
 [7 8 9 7 8 9 7 8 9]
 [1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6]
 [7 8 9 7 8 9 7 8 9]]


### Access Array

- [NumPy - Basic Slicing and Indexing](https://numpy.org/devdocs/reference/arrays.indexing.html?highlight=slicing#basic-slicing-and-indexing)


In [23]:
x = np.arange(1,10,1).reshape(3,3)

print('Array: \n', x )
print('First row: ', x[0] )
print('Last row: ', x[-1] )
print('2nd element of 2nd row: ', x[1,1] )

Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
First row:  [1 2 3]
Last row:  [7 8 9]
2nd element of 2nd row:  5


## Glossary

### General Purpose

- `numpy.ndarray.dtype` - Return the data-type of the elements of the array. Remember, arrays are homogeneous.
- `numpy.ndarray.ndim` - Return the number of array-dimensions (rank), e.g., it will return 2 for a 4x3 array.
- `numpy.ndarray.shape` - Return a tuple representing the array dimensions, e.g., it will return (rows,columns) for a rank 2 array.
- `numpy.ndarray.size` - Return the number of elements present in the array.
- `numpy.save` - Save an array to .npy (numpy) format.
- `numpy.load` - Load array from the .npy files.
- `numpy.random.random` - Return random floats values from the interval [0.0, 1.0), in a specified shape.
- `numpy.random.randint` - Return random integers from the half-open interval [a, b), in a specified shape.
- `numpy.random.normal` - Return random samples from a Gaussian (normal) distribution.
- `numpy.random.permutation` - Return a randomly permuted sequence from the given list
- `numpy.reshape` or `numpy.ndarray.reshape` - Returns an array containing the same elements with a new shape, without affecting the the original array.

### Array Creation

- `numpy.ones` - Return a new array of given shape and type, filled with 1s.
- `numpy.zeros` - Return a new array of given shape and type, filled with 0s.
- `numpy.full` - Return a new array of given shape and type, filled with a specific value.
- `numpy.eye` - Return a 2-D array with 1s on the diagonal and 0s elsewhere.
- `numpy.diag` - Extract the diagonal elements.
- `numpy.unique` - Return the sorted unique elements of an array.
- `numpy.array` - Create an n-dimensional array.
- `numpy.arange` - Return evenly spaced values within a given half-open interval [a, b).
- `numpy.linspace` - Return evenly spaced numbers over a specified interval [a,b].
- `numpy.ndarray.copy` - Returns a copy of the array.

### Category: Operating with Elements and Indices

- `numpy.insert` - Insert values along the given axis before the specified indices.
- `numpy.delete` - Return a new array, after deleting sub-arrays along a specified axis.
- `numpy.append` - Append values at the end of the specified array.
- `numpy.hstack` - Return a stacked array formed by stacking the given arrays in sequence horizontally (column-wise).
- `numpy.vstack` - Return a stacked array formed by stacking the given arrays, will be at least 2-D, in sequence vertically (row-wise).
- `numpy.sort` - Return a sorted copy of an array.
- `numpy.ndarray.sort` - Sort an array in-place.

### Category: Set Operations

- `numpy.intersect1d` - Find the intersection of two arrays.
- `numpy.setdiff1d` - Find the set difference of two arrays.
- `numpy.union1d` - Return the unique, sorted array of values that are in either of the two input arrays.

### Arithmetic and Statistical Operations

- `numpy.add` - Element-wise add given arrays
- `numpy.subtract` - Subtract arguments of given arrays, element-wise.
- `numpy.multiply` - Multiply arguments of given arrays, element-wise.
- `numpy.divide` - Returns a true division of the inputs, element-wise.
- `numpy.exp` - Calculate the exponential of all elements in the input array.
- `numpy.power` - First array elements raised to powers from second array, element-wise.
- `numpy.sqrt` - Return the non-negative square-root of an array, element-wise.
- `numpy.ndarray.min` - Return the minimum along the specified axis.
- `numpy.ndarray.max` - Return the maximum along a given axis.
- `numpy.mean` or `numpy.ndarray.mean` - Compute the arithmetic mean along the specified axis.
- `numpy.median` - Compute the median along the specified axis.